---
name: Code Quality Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-markdownlint

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-quality-tools

      - name: Install Tools (minimal)
        run: |
          echo "Installing only what's necessary..."
          npm install -g markdownlint-cli
          pip install rstcheck linkchecker

      - name: Run Markdownlint
        run: |
          markdownlint '**/*.md' || true

      - name: Run Yamllint
        run: |
          yamllint .

      - name: Run Shellcheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} + || true
